### ISSUE TITLE
macOS [id] compilation error

### ISSUE THREAD

**Issue by grylem** [duckinator/boreutils#26]
Hi
`src/id.c:75:5: error: implicit declaration of function 'getgrouplist' is invalid in C99`
`src/id.c:75:5: error: this function declaration is not a prototype`
Regards.

**Comment by duckinator** [comment]
Hey! Thanks for opening this issue. I do consider this a bug, but unfortunately I have no access to a macOS system.

Can you provide full logs of `make clean all` or `make clean test`?

In the meantime I'll ask around and see if anyone has an old mac they're willing to part with lol

**Comment by grylem** [comment]
if mv id.c id.c.orig no any problems.
`clang -std=c11 -pedantic-errors -fdiagnostics-show-option  -Werror -Weverything -Wno-missing-noreturn -Wno-unused-macros  -D_XOPEN_SOURCE=700 -D_DEFAULT_SOURCE  -fsanitize= -g $(echo bin/head | sed 's/bin\//src\//').c -o bin/head
clang -std=c11 -pedantic-errors -fdiagnostics-show-option  -Werror -Weverything -Wno-missing-noreturn -Wno-unused-macros  -D_XOPEN_SOURCE=700 -D_DEFAULT_SOURCE  -fsanitize= -g $(echo bin/id | sed 's/bin\//src\//').c -o bin/id
src/id.c:75:5: error: implicit declaration of function 'getgrouplist' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    getgrouplist(pw->pw_name, pw->pw_gid, NULL, &(group_list->size));
    ^
src/id.c:75:5: note: did you mean 'get_group_list'?
src/id.c:68:13: note: 'get_group_list' declared here
static void get_group_list(GroupList *group_list, uid_t uid) {
            ^
src/id.c:75:5: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]
    getgrouplist(pw->pw_name, pw->pw_gid, NULL, &(group_list->size));
    ^
2 errors generated.
*** Error code 1

Stop.
bmake: stopped in ...`

**Comment by duckinator** [comment]
Yeah -- the Makefile is set up to just treat each `src/*.c` file as an independent program, and it doesn't have a hard-coded list. Good to know the rest of it compiles, though!

Thanks for the logs. Looking at https://opensource.apple.com/source/Libc/Libc-1439.141.1/include/unistd.h.auto.html , it seems `getgrouplist` is declared like the following:

```c
#if __DARWIN_C_LEVEL >= __DARWIN_C_FULL
// <...>
int	 getgrouplist(const char *, int, int *, int *);
// <...>
#endif /* __DARWIN_C_LEVEL >= __DARWIN_C_FULL */
```

I found this description of `__DARWIN_C_LEVEL` but I'm unsure how accurate it is: https://stackoverflow.com/a/35093614

I'm unsure what the _proper_ fix is, or why they have it set up this way. However, if that description is accurate, you may be able to add `-D__DARWIN_C_LEVEL=__DARWIN_C_FULL` to CFLAGS ([`Makefile`, line 12](https://github.com/duckinator/boreutils/blob/main/Makefile#L12)) and get it to work.

**Comment by grylem** [comment]
alas unsuccessful, all the same errors

**Comment by duckinator** [comment]
Not sure how to approach it, then. For now I need to prepare for Tropical storm/Possibly-soon-to-be-Hurricane Henri, so will probably not look into this more until at least sometime next week.

**Comment by duckinator** [comment]
Okay, I narrowed down the problem a bit more. If you dig through macOS' `unistd.h`, it has `getgrouplist()` declared like so:

```c
#if __DARWIN_C_LEVEL >= __DARWIN_C_FULL
// ...
__BEGIN_DECLS
//...
int      getgrouplist(const char *, int, int *, int *);
//...
__END_DECLS
#endif /* __DARWIN_C_LEVEL >= __DARWIN_C_FULL */
```

This means that `__DARWIN_C_LEVEL >= __DARWIN_C_FULL` _must_ be true to use `getgrouplist`. I have confirmed that `-D_XOPEN_SOURCE=700`, which is needed to compile Boreutils on Linux, seems to be causing this condition to be false.

Still digging for the proper fix, but I suspect it's just a matter of tweaking the macro definitions in `CFLAGS`.

**Comment by duckinator** [comment]
I confirmed that specifically by taking this line, as printed by `bmake clean all`:

```
clang -std=c11 -pedantic-errors -fdiagnostics-show-option  -Werror -Weverything -Wno-missing-noreturn -Wno-unused-macros  -Wno-poison-system-directories -D_XOPEN_SOURCE=700 -D_DEFAULT_SOURCE  -fsanitize= -g $(echo bin/id | sed 's/bin\//src\//').c -o bin/id
```

And I ran two variants of it, one unmodified and one without `-D_XOPEN_SOURCE=700`:

```
% clang -std=c11 -pedantic-errors -fdiagnostics-show-option  -Werror -Weverything -Wno-missing-noreturn -Wno-unused-macros  -Wno-poison-system-directories -D_DEFAULT_SOURCE  -fsanitize= -g $(echo bin/id | sed 's/bin\//src\//').c -o bin/id

src/id.c:75:5: error: implicit declaration of function 'getgrouplist' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

<...>

% clang -std=c11 -pedantic-errors -fdiagnostics-show-option  -Werror -Weverything -Wno-missing-noreturn -Wno-unused-macros  -Wno-poison-system-directories -D_DEFAULT_SOURCE  -fsanitize= -g $(echo bin/id | sed 's/bin\//src\//').c -o bin/id                     

src/id.c:75:35: error: implicit conversion changes signedness: 'gid_t' (aka 'unsigned int') to 'int' [-Werror,-Wsign-conversion]

<...>
```

**Comment by duckinator** [comment]
I solved it by implementing my own `getgrouplist` in terms of POSIX-defined functionality (`getgrent`, `endgrent`).

**Comment by duckinator** [comment]
@grylem if you pull the latest on the `main` branch, it should work. Depending on your build environment, you may need to add `-Wno-poison-system-directories` to CFLAGS (I did on my poorly-configured macOS VM).

**Comment by grylem** [comment]
Thanks
